markdown: kramdown
pygments: true
permalink: /posts/:title
safe: true
lsi: false

baseurl: /nnadl-julia
name: Neural Networks, Deep Learning and Julia
url: http://bachase.github.io/nnadl-julia/
description: Learning Julia with some ML tasks
github: bachase